language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
# command to install dependencies
before_install:
  - pip install --upgrade pip coverage codecov
install:
  - pip install .
# command to run tests
script:
  - coverage run --source=./dpdispatcher -m unittest -v && coverage report
after_success:
  - codecov
